version: "3"

services:
  api:
    container_name: home-api
    image: josemottalopes/home-api
    build:
      context: .
      dockerfile: src/IO.Swagger/api.dockerfile
    ports:
    - "5000:5000"
    network_mode: bridge
    privileged: true
    restart: always
    devices:
      - /dev/mem:/dev/mem
    volumes:
    - /var/run/lirc:/var/run/lirc
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
