homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 0
  longitude: 0
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Camera IP Onvif
#ffmpeg:
#  ffmpeg_bin: /usr/local/bin/ffmpeg

camera:
  - platform: mjpeg
    name: Camera Oficina
    host: 192.168.20.120
    username: admin
    password: 12345678
    port: 80
    mjpeg_url: http://192.168.20.120/api/mjpegvideo.cgi?InputNumber=1&StreamNumber=1

# Try muting known issue with urllib3
logger:
  default: warning
  logs:
    urllib3.connectionpool: critical
    requests.packages.urllib3.connectionpool: critical
    homeassistant.components.media_player.sony: debug

# Weather prediction
sensor:
  - platform: yr

media_player:
  - platform: braviatv
    host: 192.168.20.103

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
